server:
  context-path: /web

spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@127.0.0.1:8521:test
      username: root
      password: root
      # 连接池配置
      initial-size: 2
      min-idle: 1
      max-active: 3
      # 连接等待超时时间
      max-wait: 10000
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0

logging:
  level:
    com:
      springboot:
        mapper: debug
