server:
  servlet:
    context-path: /search

spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@127.0.0.1:8521:test
      username: root
      password: root
      # 连接池配置
      initial-size: 2
      min-idle: 1
      max-active: 3
      # 连接等待超时时间
      max-wait: 10000
  data:
    elasticsearch:
      repositories:
        enabled: true
      # es集群的名称
      cluster-name: elasticsearch
      # es的连接地址及端口号
      cluster-nodes: 127.0.0.1:9300

#pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      springboot:
        mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml