server:
  port: 8080
  servlet:
    context-path: /rabbit

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?allowMultiQueries=true&serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      # 连接池配置
      initial-size: 2
      min-idle: 1
      max-active: 3
      # 连接等待超时时间
      max-wait: 10000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest